### ISSUE TITLE
Add publishing CI

### ISSUE THREAD

**Issue by k-collie** [ukaea/IDLBridge#19]
It would be good if the source distribution were automatically uploaded to pypi on tagged releases.

Maybe use:
```yaml
on:
  release:
    types: [created]
```

Resources:
- https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
